server:
  type: default
  maxThreads: 1024
  rootPath: '/api/*'
  applicationConnectors:
    - type: http
      port: 8094

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
  appenders:
    - type: console
      timeZone: Australia/Melbourne
    - type: file
      currentLogFilename: /tmp/noticemanager/log/notice-int.log
      archive: true
      archivedLogFilenamePattern: /tmp/noticemanager/log/notice-int-%d.log
      archivedFileCount: 5
      timeZone: Australia/Melbourne

database:
  driverClass: com.mysql.jdbc.Driver
  user: admin
  password: admin
#  url: jdbc:mysql://185.173.104.77:3306/sholop
  url: jdbc:mysql://127.0.0.1:3306/sholop
  properties:
    charSet: UTF-8
    characterEncoding: UTF-8
    useUnicode: true
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    collation: utf8_general_ci
  minSize: 4
  maxSize: 20
  maxWaitForConnection: 3s
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true
  validationQuery: "/* Health Check */ SELECT 1"
  validationQueryTimeout: 3s

